# BUILD STAGE
FROM node:20 AS build

WORKDIR /app
COPY . .

RUN npm install
RUN npm run build

# RUN STAGE
FROM nginx:alpine

COPY --from=build /app/dist/frontend /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]