apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: hotel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/nemethzzs/gde-alkfet-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_CONNECTION_STRING
              value: mongodb://hotel-mongodb:27017/hotel