name: Docker Build & Push

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # BACKEND
      - name: Build backend
        run: docker build -t ghcr.io/${{ github.repository_owner }}/gde-alkfet-backend:latest -f docker/backend/Dockerfile .

      - name: Push backend
        run: docker push ghcr.io/${{ github.repository_owner }}/gde-alkfet-backend:latest

      # FRONTEND
      - name: Build frontend
        run: docker build -t ghcr.io/${{ github.repository_owner }}/gde-alkfet-frontend:latest ./frontend

      - name: Push frontend
        run: docker push ghcr.io/${{ github.repository_owner }}/gde-alkfet-frontend:latest